export default {


   Splash:require('../assets/images/Splashscreen.png'),
   group:require('../assets/images/group.png'),
   help_outline:require('../assets/images/help_outline.png'),
   phone:require('../assets/images/phone.png'),
   shield:require('../assets/images/shield.png'),
   Account_circle:require('../assets/images/Account_circle.png'),
   emailverify:require('../assets/images/emailverify.png'),
   Acc:require('../assets/images/acc.png'),
   google:require('../assets/images/google.png'),
   fb:require('../assets/images/fb.png'),
   eyeoff:require('../assets/images/eyeoff.png'),
   eye:require('../assets/images/eye.png'),
   calendar:require('../assets/images/calendar.png'),
   location:require('../assets/images/location.png'),
   search:require('../assets/images/search.png'),
   graph:require('../assets/images/graph.png'),
   gender:require('../assets/images/gender.png'),
   edit:require('../assets/images/edit.png'),
   bio:require('../assets/images/bio.png'),
   study:require('../assets/images/study.png'),
   do:require('../assets/images/do.png'),
   political:require('../assets/images/political.png'),
   religion:require('../assets/images/religion.png'),
   interest:require('../assets/images/interest.png'),
   therapy:require('../assets/images/therapy.png'),
   heart:require('../assets/images/heart.png'),
   star:require('../assets/images/star.png'),
   beauty:require('../assets/images/beauty.png'),
   manicure:require('../assets/images/manicure.png'),
   apple:require('../assets/images/apple.png'),
   pilates:require('../assets/images/pilates.png'),
   gym:require('../assets/images/gym.png'),
   yoga:require('../assets/images/yoga.png'),
   running:require('../assets/images/running.png'),
   football:require('../assets/images/football.png'),
   tennis:require('../assets/images/tennis.png'),
   cricket:require('../assets/images/cricket.png'),
   art:require('../assets/images/art.png'),
   fashion:require('../assets/images/fashion.png'),
   makeup:require('../assets/images/makeup.png'),
   photo:require('../assets/images/photo.png'),
   singing:require('../assets/images/singing.png'),
   animation:require('../assets/images/animation.png'),
   graphic:require('../assets/images/graphic.png'),
   dancing:require('../assets/images/dancing.png'),
   standup:require('../assets/images/standup.png'),
   festival:require('../assets/images/festival.png'),
   gigs:require('../assets/images/gigs.png'),
   bars:require('../assets/images/bars.png'),
   coffee:require('../assets/images/coffee.png'),
   karaoke:require('../assets/images/karaoke.png'),
   movies:require('../assets/images/movies.png'),
   nightclub:require('../assets/images/nightclub.png'),
   park:require('../assets/images/park.png'),
   spa:require('../assets/images/spa.png'),
   theatre:require('../assets/images/theatre.png'),
   beach:require('../assets/images/beach.png'),
   bird:require('../assets/images/bird.png'),
   book:require('../assets/images/book.png'),
   cooking:require('../assets/images/cooking.png'),
   fishing:require('../assets/images/fishing.png'),
   games:require('../assets/images/games.png'),
   gardening:require('../assets/images/gardening.png'),
   tent:require('../assets/images/tent.png'),
   Videogames:require('../assets/images/Videogames.png'),
   dog:require('../assets/images/dog.png'),
   fish:require('../assets/images/fish.png'),
   cat:require('../assets/images/cat.png'),
   kyc:require('../assets/images/kyc.png'),
   down:require('../assets/images/down.png'),
   camera:require('../assets/images/camera.png'),
   arrowup:require('../assets/images/arrowup.png'),
   home:require('../assets/images/home.png'),
   people:require('../assets/images/people.png'),
   events:require('../assets/images/events.png'),
   add:require('../assets/images/add.png'),
   newsearch:require('../assets/images/newsearch.png'),
   notification:require('../assets/images/notification.png'),
   frame:require('../assets/images/frame.png'),
   loc2:require('../assets/images/loc2.png'),
   frame2:require('../assets/images/Frame2.png'),
   badminton:require('../assets/images/badminton.png'),
   dotted:require('../assets/images/dotted.png'),
   pic1:require('../assets/images/pic1.png'),
   pic2:require('../assets/images/pic2.png'),
   pic3:require('../assets/images/pic3.png'),
   pic4:require('../assets/images/pic4.png'),
   compass:require('../assets/images/compass.png'),
   map2:require('../assets/images/map2.png'),
   crosshair:require('../assets/images/crosshair.png'),
   Frameright:require('../assets/images/Frameright.png'),
   Frameleft:require('../assets/images/Frameleft.png'),
   Frame3:require('../assets/images/Frame3.png'),
   arrowleft:require('../assets/images/arrowleft.png'),
   slider:require('../assets/images/slider.png'),
   groupFrame:require('../assets/images/groupFrame.png'),
   trash:require('../assets/images/trash.png'),
   Useradd:require('../assets/images/UserAdd.png'),
   Allevent:require('../assets/images/Allevent.png'),
   arright:require('../assets/images/arright.png'),
   bTennis:require('../assets/images/bTennis.png'),
   qr:require('../assets/images/qr.png'),
   download:require('../assets/images/download.png'),
   scan:require('../assets/images/scan.png'),
   hevent:require('../assets/images/hevent.png'),
   map3:require('../assets/images/map3.png'),
   Close:require('../assets/images/Close.png'),
   qr2:require('../assets/images/qr2.png'),
   download2:require('../assets/images/download2.png'),
   deleteevent:require('../assets/images/deleteevent.png'),
   peopleactive:require('../assets/images/peopleactive.png'),
   activeadd:require('../assets/images/activeadd.png'),
   activehome:require('../assets/images/activehome.png'),
   activeevent:require('../assets/images/activeevent.png'),
   activesearch:require('../assets/images/activesearch.png'),
   monitor:require('../assets/images/monitor.png'),
   User:require('../assets/images/User.png'),
   CloseCircle:require('../assets/images/CloseCircle.png'),
   UserAdd2:require('../assets/images/UserAdd2.png'),
   UserAdd2:require('../assets/images/UserAdd2.png'),
   InfoCircle:require('../assets/images/InfoCircle.png'),
   plus:require('../assets/images/plus.png'),
   Gola:require('../assets/images/Gola.png'),
   Logo:require('../assets/images/logo.png'),
   Login:require('../assets/images/login.png'),
   gal:require('../assets/images/gallery.png'),
   map:require('../assets/images/map.png'),
   finger:require('../assets/images/finger.png'),
   Smile:require('../assets/images/Smile.png'),
   BackPro:require('../assets/images/backpro.png'),
   craft:require('../assets/images/craft.png'),
   arrow1:require('../assets/images/arrow1.jpg'),
   filter:require('../assets/images/filter.png'),
   sq:require('../assets/images/sq.png'),
   chat:require('../assets/images/chat.png'),
   repu:require('../assets/images/reputation.png'),
   like:require('../assets/images/like.png'),
   Gmap:require('../assets/images/Gmap.png'),
   kycN:require('../assets/images/kycN.png'),
   demand:require('../assets/images/demand.png'),
   radio_unselect:require('../assets/images/radio_unselect.png'),
   radio_select:require('../assets/images/radio_select.png'),
   sendButton:require('../assets/images/sendButton.png'),

   
    /********************* BottomTabs  Icons **********************/ 
    // firstActiveIcon: require('../assets/images/ic_red_add.png'),
    // firstInActiveIcon: require('../assets/images/ic_home.png'),
    // secondActiveIcon: require('../assets/images/ic_srch.png'),
    // secondInActiveIcon: require('../assets/images/ic_srch.png'),
    // thirdActiveIcon: require('../assets/images/ic_red_add.png'),
    // thirdInActiveIcon: require('../assets/images/ic_red_add.png'),
    // fourthActiveIcon: require('../assets/images/ic_notify.png'),
    // fourthInActiveIcon: require('../assets/images/ic_notify.png'),
    // fifthActiveIcon: require('../assets/images/ic_user.png'),
    // fifthInActiveIcon: require('../assets/images/ic_user.png'),
    
    // /********************* App  Icons **********************/ 
    // icLogo: require('../assets/images/logo.png'),
    // icGoogle: require('../assets/images/ic_google.png'),
    // icFacebook: require('../assets/images/ic_facebook.png'),
    // icApple: require('../assets/images/ic_apple.png'),
    // icBack: require('../assets/images/ic_back_arrow.png'),
    // icCheck: require('../assets/images/ic_blue_tick.png'),
    // icUnchek: require('../assets/images/ic_grey_tick.png'),
    // icShare: require('../assets/images/ic_direction.png'),
    // icDots: require('../assets/images/ic_dots.png'),
    // icEdit: require('../assets/images/ic_edit.png'),
    // icLink: require('../assets/images/link.png'),
    // rightArrow: require('../assets/images/right_arrow.png'),
    // icAdd: require('../assets/images/ic_add2.png'),
    // icCamera: require('../assets/images/camera.png'),
    // icCross: require('../assets/images/ic_cross.png'),

  
  };